### ISSUE TITLE
Finalize WMTS 1.0 test and adjust for simple

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ideas-testbed#3]
WMTS 1.0 test was develop outside OGC. Some refracting of the test has taken place, but it still required investigation of how well matches the requirements and conformance classes in the specification.

Also to make the test available for OGC Web Map Tile Service Simple Profile.

https://github.com/opengeospatial/ets-wmts10

**Comment by gbuehler** [comment]
OBE
